name: workspace deployment

on:
    push:
        branches: [ workspace_publish ]
jobs:
    release:
      runs-on: windows-latest
      steps:
          - name: Synapse workspace deployment
            uses: Azure/Synapse-workspace-deployment@V1.7.0
            with:
              # Provide the Synapse workspace name where you want to deploy the artifacts.
              TargetWorkspaceName: 'synapseweslbo-tst'
              # Specify the path to the workspace artifacts template.
              TemplateFile: './synapseweslbo-tst/TemplateForWorkspace.json'
              # Specify the path to the template parameter file.
              ParametersFile: './synapseweslbo-tst/TemplateParametersForWorkspace.json'
              # Provide the type of cloud environment. Valid values are: Azure Public, Azure China, Azure US Government, Azure Germany
              Environment: 'Azure Public'
              # Provide the resource group of the target Synapse workspace.
              resourceGroup: 'rg-synapse-tst'
              # Provide client id of service principal.
              clientId: ${{secrets.CLIENTID}}
              # Provide client secret of the service principal.
              clientSecret: ${{secrets.CLIENTSECRET}}
              # Provide subscription id.
              subscriptionId: '784f1210-8faf-4cf4-b9aa-e50fa084adce'
              # Provide tenant id.
              tenantId: '69621f31-cdd6-4a9d-8f8b-54d87f67e4a1'
              # Delete the artifacts which are in the workspace but not in the template.
              DeleteArtifactsNotInTemplate: 'true'
              # Use managed identity to generate the bearer token?
              managedIdentity: 'False'
