name: workspace deployment

on:
   workflow_dispatch
jobs:
    release:
      runs-on: windows-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3
           with:
               ref: workspace_publish

         - name: Synapse workspace deployment
           uses: Azure/Synapse-workspace-deployment@V1.7.0
           with:
               TargetWorkspaceName: 'synapseweslbo-tst'
               TemplateFile: './synapseweslbo-dev/TemplateForWorkspace.json'
               ParametersFile: './synapseweslbo-dev/TemplateParametersForWorkspace.json'
               Environment: 'Azure Public'
               resourceGroup: 'rg-synapse-tst'
               clientId: ${{secrets.CLIENTID}}
               clientSecret: ${{secrets.CLIENTSECRET}}
               subscriptionId: '784f1210-8faf-4cf4-b9aa-e50fa084adce'
               tenantId: '69621f31-cdd6-4a9d-8f8b-54d87f67e4a1'
               DeleteArtifactsNotInTemplate: 'true'
               managedIdentity: 'False'
               operation: 'deploy'
